ame: Predictive Maintenance CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pandas scikit-learn huggingface_hub

      - name: Prepare Data
        run: python prepare_data.py

      - name: Train Baseline Model
        run: python train.py 

      - name: Log in to Hugging Face Hub
        uses: huggingface/login@v1
        with:
          token: ${{ secrets.HUGGING_FACE_TOKEN }}

      - name: Push Model to Hub
        env:
          HF_HUB_REPO: ${{ github.repository_owner }}/${{ github.event.repository.name }}-model
        run: |
          huggingface-cli upload $HF_HUB_REPO model.joblib \
            --path_in_repo model.joblib \
            --commit-message "Push baseline model from GitHub Actions"
          echo "Model pushed to https://huggingface.co/$HF_HUB_REPO"
